---
- hosts: all
  vars:
    gui_installed: yes
    virtualbox_repo_fedora:
      source_url: http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo 
      name: virtualbox
      baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    virtualbox_repo_rhel:
      source_url: http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo 
      name: virtualbox
      baseurl: http://download.virtualbox.org/virtualbox/rpm/rhel/$releasever/$basearch
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    vagrant_url: https://releases.hashicorp.com/vagrant/1.9.3/vagrant_1.9.3_x86_64.rpm
  tasks:
    - name: exit if host is not redhat based
      when: "'{{ ansible_distribution }}' != 'CentOS' and '{{ ansible_distribution }}' != 'Red Hat Enterprise Linux' and '{{ ansible_distribution }}' != 'Fedora'"
      fail:
        msg: "Not RedHat based distribution"

    - name: set distribution variable
      when: "'{{ ansible_distribution }}' == 'CentOS' and '{{ ansible_distribution }}' == 'Red Hat Enterprise Linux'"
      set_fact:
        is_rhel: yes
        is_fedora: no

    - name: set distribution variable
      when: "'{{ ansible_distribution }}' == 'Fedora'"
      set_fact:
        is_rhel: no
        is_fedora: yes

    - name: add virtualbox key
      rpm_key:
        key: https://www.virtualbox.org/download/oracle_vbox.asc
        state: present

    - name: install fedora virtualbox repo
      tags: install
      become: yes
      when: "{{ is_fedora }}"
      yum_repository:
        name: "{{ virtualbox_repo_fedora.name }}"
        baseurl: "{{ virtualbox_repo_fedora.baseurl }}"
        enabled: "{{ virtualbox_repo_fedora.enabled }}"
        gpgcheck: "{{ virtualbox_repo_fedora.gpgcheck }}"
        repo_gpgcheck: "{{ virtualbox_repo_fedora.repo_gpgcheck }}"
        gpgkey: "{{ virtualbox_repo_fedora.gpgkey }}"
        description: virtualbox repo
        state: present

    - name: install rhel virtualbox repo
      become: yes
      when: "{{ is_rhel }}"
      yum_repository:
        name: "{{ virtualbox_repo_rhel.name }}"
        baseurl: "{{ virtualbox_repo_rhel.baseurl }}"
        enabled: "{{ virtualbox_repo_rhel.enabled }}"
        gpgcheck: "{{ virtualbox_repo_rhel.gpgcheck }}"
        repo_gpgcheck: "{{ virtualbox_repo_rhel.repo_gpgcheck }}"
        gpgkey: "{{ virtualbox_repo_rhel.gpgkey }}"
        description: virtualbox repo
        state: present

    - name: install yum on newer distros
      become: yes
      when: "{{ is_fedora }}"
      dnf:
        name: "{{ item }}"
        state: latest
      ignore_errors: yes
      with_items:
        - yum

    - name: install epel-release on centOS and RHEL
      become: yes
      tags: install
      when: "{{ is_rhel }}"
      yum:
        name: epel-release
        state: present


    - name: install default packages
      become: yes
      tags: install
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - nano
        - tree
        - mlocate
        - git
        - vim
        - python-pip
        - python2-winrm
        - libselinux-python
        - tmux
        - tmux-powerline

    - name: install gui packages not in standard repo
      tags: install
      become: yes
      when: "{{ gui_installed }}"
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - gnome-tweak-tool
        - vlc
        - VirtualBox

    - name: install vagrant
      tags: install
      become: yes
      yum:
        name: "{{ vagrant_url }}"
        state: present

    # configure Gnome3 shell extensions
    - name: backslide
      shell: "gnome-shell-extension-tool -e {{ item }}"
      with_items:
        - backslide@codeisland.org
        - drop-down-terminal@gs-extensions.zzrough.org
        - native-window-placement@gnome-shell-extensions.gcampax.github.com
        - steal-my-focus@kagesenshi.org
        - dash-to-dock@micxgx.gmail.com
        - messagingmenu@screenfreeze.net
        - openweather-extension@jenslody.de
        - topIcons@adel.gadllah@gmail.com

    - name: add colors to bash_profile
      tags: bash
      blockinfile:
        dest: '~/.bash_profile'
        create: yes
        backup: yes
        state: present
        block: |
          # Bash Colors
          # Multi-line Prompts with Colours
          export LSCOLORS=GxFxCxDxBxegedabagaced
          export PS1="\033[01;31m[ \033[01;36m\u\033[00m@\[\033[01;32m\h:\033[01;33m\w\033[00m\033[01;31m ]\033[00m\n\$ "
          export CLICOLOR=1




