---
- name: add colors to bash_profile
  tags: bash
  blockinfile: 
    path: ~/.bash_profile
    create: yes
    backup: yes
    state: present
    block: |
      # Bash Colors
      # Multi-line Prompts with Colours
      export LSCOLORS=GxFxCxDxBxegedabagaced
      export PS1="\033[01;31m[ \033[01;36m\u\033[00m@\[\033[01;32m\h:\033[01;33m\w\033[00m\033[01;31m ]\033[00m\n\$ "
      export CLICOLOR=1
 
- name: install default packages
  tags: install
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum:
    name: "{{ item }}"
    state: lastest
    update_cache: yes
  with_items:
    - nano
    - tree
    - mlocate
    - git
    - vim

- name: configure vim
  tags: vim
  
   
